### ISSUE TITLE
🐛 BUG:

### ISSUE THREAD

**Issue by Mariwan001** [withastro/compiler#1044]
### What version of `@astrojs/compiler` are you using?

last vrsion

### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

that is the error: Use dark theme
UnknownCompilerError
Unknown compiler error.
Cannot read properties of undefined (reading 'exports')
[See Docs Reference](https://docs.astro.build/en/reference/errors/unknown-compiler-error/)
This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
pages/index.astro
Open in editor

import DefaultLayout from "../layouts/Default.astro";
import { HeaderSection } from "../sections/Header";
import {HeroSection} from "../sections/Hero";
import {FeaturesCardsSection} from "../sections/FeaturesCards"
---

<DefaultLayout>
  <HeaderSection />  
  <HeroSection />
  <FeaturesCardsSections />
</DefaultLayout>
Stack Trace
TypeError: Cannot read properties of undefined (reading 'exports')
    at syscall/js.valueNew (file:///C:/Users/Mariwan_IT/Downloads/frontend-tribe-dark-saas-blockchain-site-resource-bundle/frontend-tribe-dark-saas-blockchain-site-template/node_modules/@astrojs/compiler/dist/chunk-W5DTLHV4.js:1:4526)
    at wasm://wasm/01391162:wasm-function[1568]:0x168de9
    at wasm://wasm/01391162:wasm-function[1567]:0x168b15
    at wasm://wasm/01391162:wasm-function[2536]:0x357e3a
    at wasm://wasm/01391162:wasm-function[1543]:0x164c07
    at wasm://wasm/01391162:wasm-function[204]:0x1d038
    at wasm://wasm/01391162:wasm-function[1169]:0xfab11
    at d._resume (file:///C:/Users/Mariwan_IT/Downloads/frontend-tribe-dark-saas-blockchain-site-resource-bundle/frontend-tribe-dark-saas-blockchain-site-template/node_modules/@astrojs/compiler/dist/chunk-W5DTLHV4.js:1:6412)
    at Object.transform (file:///C:/Users/Mariwan_IT/Downloads/frontend-tribe-dark-saas-blockchain-site-resource-bundle/frontend-tribe-dark-saas-blockchain-site-template/node_modules/@astrojs/compiler/dist/chunk-W5DTLHV4.js:1:6575)
    at file:///C:/Users/Mariwan_IT/Downloads/frontend-tribe-dark-saas-blockchain-site-resource-bundle/frontend-tribe-dark-saas-blockchain-site-template/node_modules/@astrojs/compiler/dist/node/index.js:1:830

### Link to Minimal Reproducible Example

http://localhost:4321/

**Comment by Mariwan001** [comment]
ok
