### ISSUE TITLE
🐛 BUG: cloudflare page build error after upgrade

### ISSUE THREAD

**Issue by dephiros** [withastro/compiler#252]
### What version of `astro` are you using?

0.22.13

### What package manager are you using?

yarn

### What operating system are you using?

Cloudflare pages (NODE 16.13.1)

### Describe the Bug

I upgraded Astro recently and run into this issue in cloudflare pages. I attempted to recreate using a initial template but cannot reproduce.
```

export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.17.linux.amd64';
--
06:58:17.227 | export PATH="/opt/buildhome/.gimme_cache/versions/go1.17.linux.amd64/bin:${PATH}";
06:58:17.227 | go version >&2;
06:58:17.227 |  
06:58:17.229 | export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.17.linux.amd64.env"
06:58:17.233 | go version go1.17 linux/amd64
06:58:17.234 | Installing missing commands
06:58:17.234 | Verify run directory
06:58:17.234 | Executing user command: yarn run build
06:58:17.386 | yarn run v1.22.17
06:58:17.417 | $ astro build
06:58:19.217 | wasm://wasm/00274c5e:1
06:58:19.217 |  
06:58:19.217 |  
06:58:19.217 | RuntimeError: null function or function signature mismatch
06:58:19.217 | at wasm://wasm/00274c5e:wasm-function[293]:0x1354b
06:58:19.217 | at wasm://wasm/00274c5e:wasm-function[300]:0x14272
06:58:19.217 | at Go._resume (file:///opt/buildhome/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:374:28)
06:58:19.217 | at file:///opt/buildhome/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:384:16
06:58:19.217 | at new Promise (<anonymous>)
06:58:19.217 | at syscall/js.valueNew (file:///opt/buildhome/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:274:54)
06:58:19.217 | at wasm://wasm/00274c5e:wasm-function[321]:0x155e3
06:58:19.217 | at wasm://wasm/00274c5e:wasm-function[821]:0x6c104
06:58:19.217 | at wasm://wasm/00274c5e:wasm-function[293]:0x1354b
06:58:19.217 | at wasm://wasm/00274c5e:wasm-function[300]:0x14272
06:58:19.422 | error Command failed with exit code 1.
06:58:19.422 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
06:58:19.431 | Failed: build command exited with code: 1

</pre><div class="c_yq c_c" style="box-sizing: border-box; display: flex; padding: 32px;"><button type="button" class="c_ll c_lm c_ln c_lo c_lp c_lq c_lr c_ls c_lt c_lu c_lv c_lw c_lx c_ly c_ab c_r c_s c_kt c_fg c_eq c_lz c_ma c_mb c_mc c_gh c_gj c_md c_me c_mf c_mg c_mh c_mi c_mj c_mk c_m c_t c_ml c_mm c_mn c_aq c_mo c_mp c_bf c_ig c_em c_ih c_hn c_bl c_bh c_go c_gp c_mq c_mr c_ms c_ff c_fv c_mt" style="box-sizing: border-box; font-size: 14px; font-family: -apple-system, system-ui, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; border: 0px solid currentcolor; position: relative; align-items: center; -webkit-box-align: center; justify-content: center; -webkit-box-pack: center; text-align: center; cursor: pointer; user-select: none; white-space: nowrap; padding: 8px 16px; margin: 0px 0px 0px auto; line-height: 1.2; font-weight: 400; display: inline-flex; border-radius: 5px; opacity: inherit; pointer-events: auto; transition-property: background-color, border-color, color; transition-duration: 200ms; transition-timing-function: ease; max-width: initial; float: none; background-color: rgb(0, 81, 195); color: rgb(242, 242, 242); width: auto;"><span style="box-sizing: border-box;">Retry deployment</span></button></div></div></div></div></div></main><footer class="c_b c_hk c_hl c_bl c_bh c_hm c_gi c_gj c_gf" style="box-sizing: border-box; background-color: rgb(255, 255, 255); padding: 32px 16px; border-color: rgb(217, 217, 217); border-top-width: 1px; border-top-style: solid; margin-top: 32px; color: rgb(49, 49, 49); font-family: -apple-system, system-ui, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="c_hn c_ho c_c c_hp c_hq" style="box-sizing: border-box; display: flex; margin-left: auto; margin-right: auto; max-width: 64rem; flex-wrap: wrap;"><div class="c_gq c_hr c_hs c_ht" style="box-sizing: border-box; margin-bottom: 16px; width: 204.797px;"><dl class="c_cc c_ff c_hu" style="box-sizing: border-box; list-style: none; margin-left: 0px; font-size: 14px;"><br class="Apple-interchange-newline">
```

### Link to Minimal Reproducible Example

Try to reproduce with a new astro site and no luck :(

**Comment by jonathantneal** [comment]
[Related post on Discord](https://canary.discord.com/channels/830184174198718474/933400101286739978)

> I'm getting RuntimeError: null function or function signature mismatch on builds in Netlify, astro 0.22.14 -- not sure if this is something wrong with Netlify or Astro. More details from the log:
> ```
> 8:32:56 AM: > astro build
> 8:32:59 AM: wasm://wasm/00278716:1
> 8:32:59 AM: RuntimeError: null function or function signature mismatch
> 8:32:59 AM:     at wasm://wasm/00278716:wasm-function[293]:0x1354c
> 8:32:59 AM:     at wasm://wasm/00278716:wasm-function[300]:0x14273
> 8:32:59 AM:     at Go._resume (file:///opt/build/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:374:28)
> 8:32:59 AM:     at file:///opt/build/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:384:16
> 8:32:59 AM:     at new Promise (<anonymous>)
> 8:32:59 AM:     at syscall/js.valueNew (file:///opt/build/repo/node_modules/@astrojs/compiler/node/wasm_exec.js:274:54)
> 8:32:59 AM:     at wasm://wasm/00278716:wasm-function[321]:0x155e4
> 8:32:59 AM:     at wasm://wasm/00278716:wasm-function[821]:0x6c13c
> 8:32:59 AM:     at wasm://wasm/00278716:wasm-function[293]:0x1354c
> 8:32:59 AM:     at wasm://wasm/00278716:wasm-function[300]:0x14273
> ```

**Comment by natemoo-re** [comment]
Closing in favor of https://github.com/withastro/compiler/issues/256
