### ISSUE TITLE
Bug track: nil pointer dereference

### ISSUE THREAD

**Issue by boehs** [withastro/compiler#256]
### What operating system are you using?

Linux

### Describe the Bug

Recently, a wave of support threads in discord have been created discussing an issue. It has been impossible to reproduce, as it only occurs on certain linux devices. Known platforms issue *may* occur on

- some devices running Arch Linux
- Cloudflare
- Netlify
- Vercel

(note, using one of these platforms is not enough to trigger this bug, there are other unknown conditions that lead it to work on some devices but not others)

---

The following related errors can be experienced based on the contents of a file:

1.

```
wasm://wasm/0027!!!!!:1
RuntimeError: null function or function signature mismatch
    at wasm://wasm/00273ac2:wasm-function[293]:0x135!!
    at wasm://wasm/00273ac2:wasm-function[300]:0x142!!
    at Go._resume (file:///home/evan/.local/share/pnpm-global/5/node_modules/.pnpm/@astrojs+compiler@0.7.4/node_modules/@astrojs/compiler/node/wasm_exec.js:374:28)
    at file:///home/evan/.local/share/pnpm-global/5/node_modules/.pnpm/@astrojs+compiler@0.7.4/node_modules/@astrojs/compiler/node/wasm_exec.js:384:16
    at new Promise (<anonymous>)
    at syscall/js.valueNew (file:///home/evan/.local/share/pnpm-global/5/node_modules/.pnpm/@astrojs+compiler@0.7.4/node_modules/@astrojs/compiler/node/wasm_exec.js:274:54)
    at wasm://wasm/0027!!!!:wasm-function[321]:0x155!!
    at wasm://wasm/0027!!!!:wasm-function[821]:0x6!!!!
    at wasm://wasm/0027!!!!:wasm-function[293]:0x135!!
    at wasm://wasm/0027!!!!:wasm-function[300]:0x142!!
```

(note: ! indicates inconsistencies between reports)

2.

`RuntimeError: Error: Uh oh, the Astro compiler encountered an unrecoverable error!`

3.

Most common!

```
panic: runtime error: nil pointer dereference
RuntimeError: Error: Uh oh, the Astro compiler encountered an unrecoverable error!
```

---

Working versions are also inconsistent. In my testing, I found the following astro versions

- 0.22.14
- 0.22.3
- <0.22.1
- Going from `0.22.15` -> `0.22.16` breaks the compiler, then downgrading to `0.22.15` does not fix it. The only way to fix it is to downgrade to `0.22.3` than upgrade to `0.22.15`.

to be the working versions, however in #252 it was reported that those versions were not working and the working version of astro was `0.21.13`

@johnnytest4real reports `0.22.14` to be broken however, and says his magic version is `0.22.11`

@Princesseuh says (nooo, contrary to my experience) that `0.22.16` was working and `0.22.20` is broken

@adamdbradley was the first victim of this issue on vercel, when he was running `^23.0-next.1`

---

These related bugs all seem to relate to the bytes in a given file, but it is not yet understood what exactly causes it. The common theory is the size of the file: in my case and one of the discord user's cases

- Removing/Adding characters sometimes fixes the issue
- Hotswapping them never fixes the issue

Here is a video of this

https://i.boehs.org/raw/astrobeingmean1.mp4

and @jonathantneal describing further https://canary.discord.com/channels/830184174198718474/931317508609282121/931359293603741757

...

Others think it may have to do with unicode handling, like 🗨️ emojis (hi @jonathantneal ;)). @Princesseuh  says that removing her emojis (rip emojis) fixed it.

---

This bug is hard to fix because it's hard to track down. Please report additional information in the comments, this issue will be kept up to date as new information arives

---

Linked:

- #255 
- #252 
- https://canary.discord.com/channels/830184174198718474/931317508609282121
- https://canary.discord.com/channels/830184174198718474/930665308409192488
- https://canary.discord.com/channels/830184174198718474/872574301046439956/931361468966912010
- https://canary.discord.com/channels/830184174198718474/938928641142849576

### Link to Minimal Reproducible Example

If anyone manages to reproduce this I will hug them and break into tears

**Comment by natemoo-re** [comment]
Thank you for condensing all of these into one issue! As you mentioned, this is really elusive and hard to track down but I'm attempting a few things. Hopefully will have more to share soon.

**Comment by johnnytest4real** [comment]
FYI - I reverted astro 0.22.14 to 0.22.11 and my build completed successfully on Netlify.

**Comment by Princesseuh** [comment]
[This file](https://github.com/Princesseuh/princesseuh.dev/blob/52a766c198ea17a2c012c509f85c3746a24151e5/src/data/projects.ts) cause this issue in my project. Again, like the other cases it work in local but crashes on Netlify with the following message:

> RuntimeError: Error: Uh oh, the Astro compiler encountered an unrecoverable error!

It worked before [this commit](https://github.com/Princesseuh/princesseuh.dev/commit/52a766c198ea17a2c012c509f85c3746a24151e5) however that commit also upgrade Astro from `0.22.16` to `0.22.20` which might be the real cause of this issue and not the changes to the file itself. A bit unfortunate for a repro that this commit both upgraded Astro and changed that file 😓

**Comment by aFuzzyBear** [comment]
Hello, just a further update with more information pertaining to this issue that has surfaced from the Support thread raised by @Princesseuh in discord see [here](https://discord.com/channels/830184174198718474/938928641142849576).
Users have been reporting issues within their own project relating to similar experiences, having listened to the feedback that has been received on the thread I wish to raise your attentions to the following summary:
"Erika(she/her) has provided confirmation of a surrogate pair issue with the compiler."
This was further confirmed by @natemoo-re  to be: "Unicode issue has been identified within the compiler", 

I have asked for further evidence of this behaviour be collected on the support thread, where there is compelling evidence to help support this particular line of reasoning. Hoping that this should prove useful to helping the maintainers in tackling this particular problem,

Many Thanks,

**Comment by natemoo-re** [comment]
We have verified that a number of good reproductions are fixed by #291. I'm confident this issue will be closed by that PR. Very, very good news! 🎉 

Thanks for being so thorough and patient, y'all.

Please re-open this issue if I'm wrong, but I sincerely hope that I'm not.

**Comment by boehs** [comment]
Could we hold off on closing for a week or so?

**Comment by natemoo-re** [comment]
Happy to leave this open, yes. I wasn't intending to close it until this fix is actually released in Astro core and in your hands.

**Comment by natemoo-re** [comment]
# A fix has been released in `astro@0.23.0-next.9`!

See https://github.com/withastro/astro/pull/2599

Please upgrade to `astro@0.23.0-next.9` to verify if this issue persists.

**Comment by natemoo-re** [comment]
Going to close this as things have been quiet since 0.23. Thanks everyone!
