### ISSUE TITLE
🐛 BUG: `@astrojs/compiler` panic

### ISSUE THREAD

**Issue by nakorndev-cvd** [withastro/compiler#626]
### What version of `astro` are you using?

1.6.7

### Are you using an SSR adapter? If so, which one?

None

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

`@astrojs/compiler` encountered an unrecoverable error when compiling the following file.

Please see stackblitz.com at file `src/pages/index.astro` my code will bug at line `121`. You can try removing this line and the webpage will be running normally. Still finding what makes this problem. Thanks and sorry for my English.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fnkjr2?file=src/pages/index.astro

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by bluwy** [comment]
I wonder if it's the same cause as https://github.com/withastro/compiler/issues/624

**Comment by nakorndev-cvd** [comment]
Update what I found. It should be linked to this line as the error shown on the console. https://github.com/withastro/compiler/blob/e378f0b61e30d4926181257433fa309f6604feb7/internal/parser.go#L1754

![image](https://user-images.githubusercontent.com/103918183/201796618-59c7ad6f-3330-4178-ac8d-f364cb0e5baf.png)

**Comment by nakorndev-cvd** [comment]
Workaround for me I stop using any `<table>` `<tbody>` `<tr>` `<td>` that related to the table tag. Change all to `<div>` and use the Tailwind display class instead to get my website working again. I don't know Golang code but I can point this compiler on the table tag should be a bug somehow.

Hope it is will be fix soon.

![image](https://user-images.githubusercontent.com/103918183/201797765-af481147-11e8-4531-9493-e647609bbe05.png)

**Comment by nakorndev-cvd** [comment]
@natemoo-re Can you reopen this issue? Still have the same problem for me after I update `"@astrojs/compiler": "^0.29.17"` and `"astro": "^1.6.10",`

I update package.json at https://stackblitz.com/edit/github-fnkjr2?file=src%2Fpages%2Findex.astro,package.json you can see the result and error could be related to line 1754.

https://github.com/withastro/compiler/blob/%40astrojs/compiler%400.29.17/internal/parser.go#L1750-L1754

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x0 addr=0x0 pc=0x0]

goroutine 17 [running]:
github.com/withastro/compiler/internal.inTableIM(0x6c2240)
        github.com/withastro/compiler/internal/parser.go:1754 +0x12
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x6c2240)
        github.com/withastro/compiler/internal/parser.go:2935 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x6c2240)
        github.com/withastro/compiler/internal/parser.go:2962 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x76d60, 0x4309c0}, {0x42bb00, 0x1, 0x1})
        github.com/withastro/compiler/internal/parser.go:3035 +0x1c
main.Transform.func1.1.1({0x6f0000, 0x1d08}, 0x6c2120, 0x4bc790, 0x40a768, {{}, 0x7ff8000400000106, 0x6a8da8})  
        ./astro-wasm.go:291 +0xb
created by main.Transform.func1.1
        ./astro-wasm.go:288 +0x3
```
