### ISSUE TITLE
🐛 BUG: "fatal error: out of memory"

### ISSUE THREAD

**Issue by SeanMcP** [withastro/compiler#761]
### What version of `@astrojs/compiler` are you using?

1.1.0

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

My site no longer builds nor runs in the development server. In both instances I get a `fatal error: out of memory`. This problem came up suddenly: one morning everything was working, but in the evening nothing would run.

The full build and development errors are below, but here are the main errors:

```
runtime: out of memory: cannot allocate 4194304-byte block (3801088 in use)
fatal error: out of memory

fatal error: out of memory allocating heap arena metadata
```

Astro functions as expected on my Mac computer, and it used to work on my Windows computer. So it might be dependent on the computer's available memory which would make reproduction difficult. But I am out of my depth in the Go part of this project.

<details>
<summary><code>astro build</code></summary>

```
runtime: out of memory: cannot allocate 4194304-byte block (4030464 in use)
fatal error: out of memory

goroutine 32 [running]:
runtime.throw({0x3e1ce, 0xd})
        runtime/panic.go:1047 +0x3 fp=0x4fc698 sp=0x4fc670 pc=0x12260003
runtime.(*mcache).allocLarge(0x220108, 0x25fc0, 0x0)
        runtime/mcache.go:235 +0x37 fp=0x4fc6e8 sp=0x4fc698 pc=0x10e70037
runtime.mallocgc(0x25fc0, 0x2a600, 0x1)
        runtime/malloc.go:1029 +0x8b fp=0x4fc768 sp=0x4fc6e8 pc=0x109f008b
runtime.newarray(0x2a600, 0x23c)
        runtime/malloc.go:1224 +0x11 fp=0x4fc790 sp=0x4fc768 pc=0x10a20011
runtime.makeBucketArray(0x1d060, 0x9, 0x0)
        runtime/map.go:363 +0x3a fp=0x4fc7c0 sp=0x4fc790 pc=0x10ae003a
runtime.hashGrow(0x1d060, 0x762d50)
        runtime/map.go:1051 +0xc fp=0x4fc808 sp=0x4fc7c0 pc=0x10b6000c
runtime.mapassign_faststr(0x1d060, 0x762d50, {0x7f05a0, 0xa})
        runtime/map_faststr.go:276 +0x1f fp=0x4fc878 sp=0x4fc808 pc=0x10c9001f
github.com/withastro/compiler/lib/esbuild/helpers.MakeTypoDetector({0x7b8000, 0x13c, 0x13c})
        github.com/withastro/compiler/lib/esbuild/helpers/typos.go:16 +0x2d fp=0x4fc8f0 sp=0x4fc878 pc=0x173f002d
github.com/withastro/compiler/lib/esbuild/css_ast.MaybeCorrectDeclarationTypo({0x7b646b, 0xd})
        github.com/withastro/compiler/lib/esbuild/css_ast/css_decl_table.go:669 +0x22 fp=0x4fca00 sp=0x4fc8f0 pc=0x177d0022
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseDeclaration(0x4fcee8)
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:1577 +0x5f fp=0x4fcbc0 sp=0x4fca00 pc=0x17b3005f
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseListOfDeclarations(0x4fcee8)
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:311 +0x2e fp=0x4fcc38 sp=0x4fcbc0 pc=0x17a6002e
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseSelectorRuleFrom(0x4fcee8, 0x13b, {{{0x0}, 0x0}, 0x0})
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:1450 +0xb fp=0x4fccd0 sp=0x4fcc38 pc=0x17b1000b
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseListOfRules(0x4fcee8, {0x1, 0x1})
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:274 +0x37 fp=0x4fcd60 sp=0x4fccd0 pc=0x17a50037
github.com/withastro/compiler/lib/esbuild/css_parser.Parse({0x49fe0, 0x0, 0x0, 0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x7b6000, ...}, ...}, ...)
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:51 +0x6 fp=0x4fd1c0 sp=0x4fcd60 pc=0x17a10006
github.com/withastro/compiler/internal/transform.ScopeStyle({0x40d120, 0x1, 0x1}, {{0x764910, 0x8}, {0x62e900, 0x53}, {0x776030, 0x24}, {0x487b00, ...}, ...})
        github.com/withastro/compiler/internal/transform/scope-css.go:45 +0x41 fp=0x4fd5e0 sp=0x4fd1c0 pc=0x18ae0041
github.com/withastro/compiler/internal/transform.Transform(0x6e98c0, {{0x764910, 0x8}, {0x62e900, 0x53}, {0x776030, 0x24}, {0x487b00, 0x15}, {0x7648dc, ...}, ...}, ...)
        github.com/withastro/compiler/internal/transform/transform.go:30 +0x6 fp=0x4fd770 sp=0x4fd5e0 pc=0x18b30006
main.Transform.func1.1.1()
        ./astro-wasm.go:307 +0x21 fp=0x4fdfe0 sp=0x4fd770 pc=0x19130021
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4fdfe8 sp=0x4fdfe0 pc=0x13ef0001
created by main.Transform.func1.1
        ./astro-wasm.go:273 +0x16

goroutine 1 [chan receive]:
runtime.gopark(0x4a0b8, 0x4320b8, 0xe, 0x17, 0x2)
        runtime/proc.go:363 +0x27 fp=0x44bd38 sp=0x44bd10 pc=0x124d0027
runtime.chanrecv(0x432060, 0x0, 0x1)
        runtime/chan.go:583 +0x7c fp=0x44bdc0 sp=0x44bd38 pc=0x1062007c
runtime.chanrecv1(0x432060, 0x0)
        runtime/chan.go:442 +0x2 fp=0x44bde8 sp=0x44bdc0 pc=0x10610002
main.main()
        ./astro-wasm.go:30 +0xd fp=0x44bf80 sp=0x44bde8 pc=0x18ff000d
runtime.main()
        runtime/proc.go:250 +0x35 fp=0x44bfe0 sp=0x44bf80 pc=0x12480035
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x44bfe8 sp=0x44bfe0 pc=0x13ef0001

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4a230, 0x1ee100, 0x11, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x424fb8 sp=0x424f90 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.forcegchelper()
        runtime/proc.go:302 +0x17 fp=0x424fe0 sp=0x424fb8 pc=0x124b0017
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x424fe8 sp=0x424fe0 pc=0x13ef0001
created by runtime.init.5
        runtime/proc.go:290 +0x2

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4a230, 0x1ee3e0, 0xc, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x4257a8 sp=0x425780 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.bgsweep(0x42a000)
        runtime/mgcsweep.go:278 +0xf fp=0x4257d0 sp=0x4257a8 pc=0x117a000f
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x2 fp=0x4257e0 sp=0x4257d0 pc=0x11000002
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4257e8 sp=0x4257e0 pc=0x13ef0001
created by runtime.gcenable
        runtime/mgc.go:178 +0x8

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4a230, 0x1ee4c0, 0xd, 0x14, 0x2)
        runtime/proc.go:363 +0x27 fp=0x425f80 sp=0x425f58 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.(*scavengerState).park(0x1ee4c0)
        runtime/mgcscavenge.go:389 +0xd fp=0x425fa8 sp=0x425f80 pc=0x1162000d
runtime.bgscavenge(0x42a000)
        runtime/mgcscavenge.go:617 +0x4 fp=0x425fd0 sp=0x425fa8 pc=0x11670004
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x2 fp=0x425fe0 sp=0x425fd0 pc=0x10ff0002
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x425fe8 sp=0x425fe0 pc=0x13ef0001
created by runtime.gcenable
        runtime/mgc.go:179 +0xe

goroutine 5 [finalizer wait]:
runtime.gopark(0x4a230, 0x20afe8, 0x10, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x424738 sp=0x424710 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.runfinq()
        runtime/mfinal.go:180 +0x21 fp=0x4247e0 sp=0x424738 pc=0x10f70021
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4247e8 sp=0x4247e0 pc=0x13ef0001
created by runtime.createfing
        runtime/mfinal.go:157 +0x5

goroutine 6 [waiting]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x1)
        runtime/proc.go:363 +0x27 fp=0x438f90 sp=0x438f68 pc=0x124d0027
runtime.handleEvent()
        runtime/lock_js.go:257 +0x1b fp=0x438fe0 sp=0x438f90 pc=0x1096001b
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x438fe8 sp=0x438fe0 pc=0x13ef0001
created by runtime.beforeIdle
        runtime/lock_js.go:207 +0x1a
exit code: 2
Go program has already exited
```

</details>

<details>
<summary><code>astro dev</code></summary>

```
fatal error: out of memory allocating heap arena metadata

runtime stack:
runtime.throw({0x46a34, 0x2c})
        runtime/panic.go:1047 +0x3 fp=0x20dca8 sp=0x20dc80 pc=0x12260003
runtime.(*mheap).sysAlloc(0x1f43e0, 0x400000)
        runtime/malloc.go:689 +0x39 fp=0x20dd48 sp=0x20dca8 pc=0x109b0039
runtime.(*mheap).grow(0x1f43e0, 0x13)
        runtime/mheap.go:1418 +0xa fp=0x20ddc0 sp=0x20dd48 pc=0x11a2000a
runtime.(*mheap).allocSpan(0x1f43e0, 0x13, 0x0, 0x0)
        runtime/mheap.go:1199 +0x41 fp=0x20de70 sp=0x20ddc0 pc=0x11a10041
runtime.(*mheap).alloc.func1()
        runtime/mheap.go:918 +0xb fp=0x20deb8 sp=0x20de70 pc=0x119b000b
runtime.systemstack()
        runtime/asm_wasm.s:169 +0x2 fp=0x20dec0 sp=0x20deb8 pc=0x13c60002
runtime.mstart()
        runtime/asm_wasm.s:27 fp=0x20dec8 sp=0x20dec0 pc=0x13c20000

goroutine 30 [running]:
runtime.systemstack_switch()
        runtime/asm_wasm.s:180 fp=0x4fc658 sp=0x4fc650 pc=0x13c70000
runtime.(*mheap).alloc(0x1f43e0, 0x13, 0x0)
        runtime/mheap.go:912 +0x2 fp=0x4fc698 sp=0x4fc658 pc=0x119a0002
runtime.(*mcache).allocLarge(0x220108, 0x25fc0, 0x0)
        runtime/mcache.go:233 +0xb fp=0x4fc6e8 sp=0x4fc698 pc=0x10e7000b
runtime.mallocgc(0x25fc0, 0x2a600, 0x1)
        runtime/malloc.go:1029 +0x8b fp=0x4fc768 sp=0x4fc6e8 pc=0x109f008b
runtime.newarray(0x2a600, 0x23c)
        runtime/malloc.go:1224 +0x11 fp=0x4fc790 sp=0x4fc768 pc=0x10a20011
runtime.makeBucketArray(0x1d060, 0x9, 0x0)
        runtime/map.go:363 +0x3a fp=0x4fc7c0 sp=0x4fc790 pc=0x10ae003a
runtime.hashGrow(0x1d060, 0x7880c0)
        runtime/map.go:1051 +0xc fp=0x4fc808 sp=0x4fc7c0 pc=0x10b6000c
runtime.mapassign_faststr(0x1d060, 0x7880c0, {0x7c0390, 0x9})
        runtime/map_faststr.go:276 +0x1f fp=0x4fc878 sp=0x4fc808 pc=0x10c9001f
github.com/withastro/compiler/lib/esbuild/helpers.MakeTypoDetector({0x78c000, 0x13c, 0x13c})
        github.com/withastro/compiler/lib/esbuild/helpers/typos.go:16 +0x2d fp=0x4fc8f0 sp=0x4fc878 pc=0x173f002d
github.com/withastro/compiler/lib/esbuild/css_ast.MaybeCorrectDeclarationTypo({0x782eeb, 0xd})
        github.com/withastro/compiler/lib/esbuild/css_ast/css_decl_table.go:669 +0x22 fp=0x4fca00 sp=0x4fc8f0 pc=0x177d0022
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseDeclaration(0x4fcee8)
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:1577 +0x5f fp=0x4fcbc0 sp=0x4fca00 pc=0x17b3005f
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseListOfDeclarations(0x4fcee8)
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:311 +0x2e fp=0x4fcc38 sp=0x4fcbc0 pc=0x17a6002e
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseSelectorRuleFrom(0x4fcee8, 0x13b, {{{0x0}, 0x0}, 0x0})
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:1450 +0xb fp=0x4fccd0 sp=0x4fcc38 pc=0x17b1000b
github.com/withastro/compiler/lib/esbuild/css_parser.(*parser).parseListOfRules(0x4fcee8, {0x1, 0x1})
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:274 +0x37 fp=0x4fcd60 sp=0x4fccd0 pc=0x17a50037
github.com/withastro/compiler/lib/esbuild/css_parser.Parse({0x49fe0, 0x0, 0x0, 0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x782a80, ...}, ...}, ...)
        github.com/withastro/compiler/lib/esbuild/css_parser/css_parser.go:51 +0x6 fp=0x4fd1c0 sp=0x4fcd60 pc=0x17a10006
github.com/withastro/compiler/internal/transform.ScopeStyle({0x40d058, 0x1, 0x1}, {{0x70bd90, 0x8}, {0x6d2660, 0x53}, {0x5bfcb0, 0x24}, {0x487788, ...}, ...})
        github.com/withastro/compiler/internal/transform/scope-css.go:45 +0x41 fp=0x4fd5e0 sp=0x4fd1c0 pc=0x18ae0041
github.com/withastro/compiler/internal/transform.Transform(0x6e57a0, {{0x70bd90, 0x8}, {0x6d2660, 0x53}, {0x5bfcb0, 0x24}, {0x487788, 0x15}, {0x70bd5c, ...}, ...}, ...)
        github.com/withastro/compiler/internal/transform/transform.go:30 +0x6 fp=0x4fd770 sp=0x4fd5e0 pc=0x18b30006
main.Transform.func1.1.1()
        ./astro-wasm.go:307 +0x21 fp=0x4fdfe0 sp=0x4fd770 pc=0x19130021
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4fdfe8 sp=0x4fdfe0 pc=0x13ef0001
created by main.Transform.func1.1
        ./astro-wasm.go:273 +0x16

goroutine 1 [chan receive]:
runtime.gopark(0x4a0b8, 0x4320b8, 0xe, 0x17, 0x2)
        runtime/proc.go:363 +0x27 fp=0x44bd38 sp=0x44bd10 pc=0x124d0027
runtime.chanrecv(0x432060, 0x0, 0x1)
        runtime/chan.go:583 +0x7c fp=0x44bdc0 sp=0x44bd38 pc=0x1062007c
runtime.chanrecv1(0x432060, 0x0)
        runtime/chan.go:442 +0x2 fp=0x44bde8 sp=0x44bdc0 pc=0x10610002
main.main()
        ./astro-wasm.go:30 +0xd fp=0x44bf80 sp=0x44bde8 pc=0x18ff000d
runtime.main()
        runtime/proc.go:250 +0x35 fp=0x44bfe0 sp=0x44bf80 pc=0x12480035
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x44bfe8 sp=0x44bfe0 pc=0x13ef0001

goroutine 2 [force gc (idle)]:
runtime.gopark(0x4a230, 0x1ee100, 0x11, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x424fb8 sp=0x424f90 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.forcegchelper()
        runtime/proc.go:302 +0x17 fp=0x424fe0 sp=0x424fb8 pc=0x124b0017
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x424fe8 sp=0x424fe0 pc=0x13ef0001
created by runtime.init.5
        runtime/proc.go:290 +0x2

goroutine 3 [GC sweep wait]:
runtime.gopark(0x4a230, 0x1ee3e0, 0xc, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x4257a8 sp=0x425780 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.bgsweep(0x42a000)
        runtime/mgcsweep.go:278 +0xf fp=0x4257d0 sp=0x4257a8 pc=0x117a000f
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x2 fp=0x4257e0 sp=0x4257d0 pc=0x11000002
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4257e8 sp=0x4257e0 pc=0x13ef0001
created by runtime.gcenable
        runtime/mgc.go:178 +0x8

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x4a230, 0x1ee4c0, 0xd, 0x14, 0x2)
        runtime/proc.go:363 +0x27 fp=0x425f80 sp=0x425f58 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.(*scavengerState).park(0x1ee4c0)
        runtime/mgcscavenge.go:389 +0xd fp=0x425fa8 sp=0x425f80 pc=0x1162000d
runtime.bgscavenge(0x42a000)
        runtime/mgcscavenge.go:617 +0x4 fp=0x425fd0 sp=0x425fa8 pc=0x11670004
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x2 fp=0x425fe0 sp=0x425fd0 pc=0x10ff0002
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x425fe8 sp=0x425fe0 pc=0x13ef0001
created by runtime.gcenable
        runtime/mgc.go:179 +0xe

goroutine 5 [finalizer wait]:
runtime.gopark(0x4a230, 0x20afe8, 0x10, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x424738 sp=0x424710 pc=0x124d0027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.runfinq()
        runtime/mfinal.go:180 +0x21 fp=0x4247e0 sp=0x424738 pc=0x10f70021
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4247e8 sp=0x4247e0 pc=0x13ef0001
created by runtime.createfing
        runtime/mfinal.go:157 +0x5

goroutine 6 [waiting]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x1)
        runtime/proc.go:363 +0x27 fp=0x438f90 sp=0x438f68 pc=0x124d0027
runtime.handleEvent()
        runtime/lock_js.go:257 +0x1b fp=0x438fe0 sp=0x438f90 pc=0x1096001b
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x438fe8 sp=0x438fe0 pc=0x13ef0001
created by runtime.beforeIdle
        runtime/lock_js.go:207 +0x1a
exit code: 2
Go program has already exited
```

</details>

### Link to Minimal Reproducible Example

https://github.com/seanmcp/seanmcp.com

**Comment by SeanMcP** [comment]
Hmm, I'm not sure how to do that. I tried all of these, but none seemed to have any effect:

```
node node_modules/astro/astro.js build --max-old-space-size=1536
npx astro build --max-old-space-size=1536
npx astro build -- --max-old-space-size=1536
```

But after running `npx astro build` repeatedly in the terminal, I'm noticing different outputs. I sometimes see another memory issue, but specifically with WebAssembly. I also see a transform error that seems to have issue with code that doesn't exist in my project. The original error comes up frequently too.

And every once in a while, maybe 1/10 runs, the build executes successfully. Very strange.

<details>
<summary><code>RangeError: WebAssembly.instantiate(): Out of memory: wasm memory</code></summary>

```
npx astro build
(node:14080) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
07:08:48 AM [content] Types generated 1.47s
07:08:48 AM [build] output target: static
07:08:48 AM [build] Collecting build info...
07:08:48 AM [build] Completed in 2.06s.
07:08:48 AM [build] Building static entrypoints...
[astro:build] WebAssembly.instantiate(): Out of memory: wasm memory
file: C:/Users/Sean McPherson/dev/seanmcp/seanmcp.com/src/pages/contact/index.astro:undefined:undefined
 error   WebAssembly.instantiate(): Out of memory: wasm memory
  Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
  File:
    C:/Users/Sean McPherson/dev/seanmcp/seanmcp.com/src/pages/contact/index.astro
  Stacktrace:
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
```

</details>

<details>
<summary>A transform "error" that doesn't exist in the code</summary>

The first line 17 in the code block below does not exist, but the second line 17 does.

```
npx astro build
(node:14112) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
07:08:01 AM [content] Types generated 1.45s
07:08:01 AM [build] output target: static
07:08:01 AM [build] Collecting build info...
07:08:01 AM [build] Completed in 2.02s.
07:08:01 AM [build] Building static entrypoints...
[astro:build] Transform failed with 1 error:
C:/Users/Sean McPherson/dev/seanmcp/seanmcp.com/src/pages/series.astro:17:9: ERROR: Unexpected newline after "throw"
file: C:/Users/Sean McPherson/dev/seanmcp/seanmcp.com/src/pages/series.astro:17:9

Unexpected newline after "throw"
15 |    const { series } = article.data;
16 |    if (!series) {
17 |      throw
   |           ^
18 |    };
19 |    if (!articlesBySeries[series]) {

 error   Unexpected newline after "throw"
  File:
    C:/Users/Sean McPherson/dev/seanmcp/seanmcp.com/src/pages/series.astro:17:9
  Code:
    16 |   if (!series) {
    > 17 |     return
         |         ^
      18 |   };
      19 |   if (!articlesBySeries[series]) {
      20 |     articlesBySeries[series] = [];
```

</details>

<details>
<summary><code>fatal error: out of memory</code></summary>

```
npx astro build
(node:4792) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
07:13:49 AM [content] Types generated 1.44s
07:13:49 AM [build] output target: static
07:13:49 AM [build] Collecting build info...
07:13:49 AM [build] Completed in 2.00s.
07:13:49 AM [build] Building static entrypoints...
runtime: out of memory: cannot allocate 4194304-byte block (3768320 in use)
fatal error: out of memory

goroutine 13 [running]:
runtime.throw({0x3e1ce, 0xd})
        runtime/panic.go:1047 +0x3 fp=0x76b2f8 sp=0x76b2d0 pc=0x12260003
runtime.(*mcache).refill(0x220108, 0x69)
        runtime/mcache.go:183 +0x27 fp=0x76b348 sp=0x76b2f8 pc=0x10e60027
runtime.(*mcache).nextFree(0x220108, 0x69)
        runtime/malloc.go:819 +0xa fp=0x76b380 sp=0x76b348 pc=0x109e000a
runtime.mallocgc(0x2170, 0x0, 0x0)
        runtime/malloc.go:1018 +0x7d fp=0x76b400 sp=0x76b380 pc=0x109f007d
runtime.slicebytetostring(0x0, 0x62e000, 0x2170)
        runtime/string.go:114 +0x7 fp=0x76b428 sp=0x76b400 pc=0x130d0007
fmt.Sprintf({0x48d8f, 0x64}, {0x76b4c8, 0x3, 0x3})
        fmt/print.go:220 +0x6 fp=0x76b478 sp=0x76b428 pc=0x15df0006
main.createSourceMapString({0x500580, 0x569}, {{0x7f0c00, 0xa51, 0xc00}, {{0x66b600, 0x1a12, 0x1b00}, {0x5b, 0x0, ...}, ...}}, ...)
        ./astro-wasm.go:436 +0x15 fp=0x76b570 sp=0x76b478 pc=0x19180015
main.createBothSourceMap({0x500580, 0x569}, {{0x7f0c00, 0xa51, 0xc00}, {{0x66b600, 0x1a12, 0x1b00}, {0x5b, 0x0, ...}, ...}}, ...)
        ./astro-wasm.go:474 +0x2 fp=0x76b770 sp=0x76b570 pc=0x191b0002
main.Transform.func1.1.1()
        ./astro-wasm.go:399 +0x3d fp=0x76bfe0 sp=0x76b770 pc=0x1913003d
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x76bfe8 sp=0x76bfe0 pc=0x13ef0001
created by main.Transform.func1.1
        ./astro-wasm.go:273 +0x16
```

</details>

**Comment by SeanMcP** [comment]
This issue was resolved after installing a larger solid-state drive on my computer. To anyone who reads this and is unable to do so: I'm sorry and I wish you the best!
