### ISSUE TITLE
🐛 BUG: error runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by ariley** [withastro/compiler#764]
### What version of `@astrojs/compiler` are you using?

8.17.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Hello,

When circleCI is trying to build it, I get the below error. I added a link to the main site, but it fails at the last build.

[astro:build] runtime error: index out of range [0] with length 0
file: /home/circleci/project/src/layouts/Header.astro:undefined:undefined
 error   runtime error: index out of range [0] with length 0
  Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
  File:
    /home/circleci/project/src/layouts/Header.astro
  Stacktrace:
goroutine 24 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x47b0e0, {0x184b158, 0x486b40})
	github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
	./astro-wasm.go:278 +0x5
panic({0x2daa0, 0x486b40})
	runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal.inBodyIM(0x47b200)
	github.com/withastro/compiler/internal/parser.go:1157 +0x658
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x47b200)
	github.com/withastro/compiler/internal/parser.go:2966 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x47b200)
	github.com/withastro/compiler/internal/parser.go:2993 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x7aa38, 0x42c440}, {0x436af0, 0x1, 0x1})
	github.com/withastro/compiler/internal/parser.go:3057 +0x1c
main.Transform.func1.1.1()
	./astro-wasm.go:283 +0xe
created by main.Transform.func1.1
	./astro-wasm.go:274 +0x16

Exited with code exit status 1

### Link to Minimal Reproducible Example

https://radfm.cloud/

**Comment by ariley** [comment]
Problem solved: my SEO section was outside the html.
