### ISSUE TITLE
🐛 BUG: Crash on Windows

### ISSUE THREAD

**Issue by ElDynamo** [withastro/compiler#786]
### What version of `@astrojs/compiler` are you using?

2.3.3

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

In component "List.astro" I get error:

```
PS C:\Users\thedy\Stronki projekty\betterize-project> npm run build

> astro-template@1.0.0 build
> astro build

12:47:13 [content] No content directory found. Skipping type generation.
12:47:13 [build] output target: static
12:47:13 [build] Collecting build info...
12:47:13 [build] Completed in 425ms.
12:47:13 [build] Building static entrypoints...
[astro:build] runtime error: index out of range [196] with length 196
file: C:/Users/thedy/Stronki projekty/betterize-project/src/components/editorjs/subcomponents/List.astro:undefined:undefined
 error   runtime error: index out of range [196] with length 196
  Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.   
  File:
    C:/Users/thedy/Stronki projekty/betterize-project/src/components/editorjs/subcomponents/List.astro
  Stacktrace:
goroutine 53 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x60f320, {0x1897958, 0x567848})
        github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
        ./astro-wasm.go:284 +0x5
panic({0x2dae0, 0x567848})
        runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal/printer.(*printer).printTextWithSourcemap(0x70f758, {0x512b60, 0xc4}, {0xd9})
        github.com/withastro/compiler/internal/printer/printer.go:72 +0x25
github.com/withastro/compiler/internal/printer.render1(0x70f758, 0x6f63c0, {0x0, 0x0, 0x4, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, ...}, ...})
        github.com/withastro/compiler/internal/printer/print-to-js.go:320 +0x18f
github.com/withastro/compiler/internal/printer.render1(0x70f758, 0x6f6140, {0x0, 0x0, 0x3, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, ...}, ...})
        github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x70f758, 0x6f6000, {0x0, 0x0, 0x2, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, ...}, ...})
        github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x70f758, 0x6bdcc0, {0x0, 0x0, 0x1, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, ...}, ...})
        github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x70f758, 0x6bd900, {0x1, 0x0, 0x0, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, ...}, ...})
        github.com/withastro/compiler/internal/printer/print-to-js.go:121 +0xc1
github.com/withastro/compiler/internal/printer.printToJs(0x70f758, 0x6bd900, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, {0x65f680, 0x31}, {0x567770, ...}, ...})
        github.com/withastro/compiler/internal/printer/print-to-js.go:72 +0x3
github.com/withastro/compiler/internal/printer.PrintToJS({0x5b4f00, 0x2fb}, 0x6bd900, 0x0, {{0x6b2c10, 0x8}, {0x6b4700, 0x62}, {0x65f680, 0x31}, ...}, ...)
        github.com/withastro/compiler/internal/printer/print-to-js.go:53 +0xc
main.Transform.func1.1.1()
        ./astro-wasm.go:401 +0x38
created by main.Transform.func1.1
        ./astro-wasm.go:280 +0x14
```

List.astro (code below)
```
---
enum Style {
    Ordered = "ordered",
    Unordered = "unordered",
}

interface Props {
    style: Style;
    items: [string];
}

const { style, items } = Astro.props;
console.log(items);
---

<div class="px-10">
    {
        () => {
            if (style == Style.Ordered) {
                return items.map((item: string, index: number) => (
                    // index + 1 is needed to start with 1 not 0
                    <p>
                        {index + 1}
                        <Fragment set:html={item} />
                    </p>
                ));
            } else {
                return items.map((item: string) => (
                    <Fragment set:html={item} />
                ));
            }
        }
    }
</div>

```
when I remove a line with comment:
```
 // index + 1 is needed to start with 1 not 0
```

then everything seems to work just fine

Warning!
Link below isn't a "minimal reproducible example".
The whole issue with code is described in this post

### Link to Minimal Reproducible Example

https://www.thislinkdoesnotexist.com

**Comment by petterhoel** [comment]
I am having the same issue. Fairly same anyways. 
- Every time on our build servers (Windows - several build agents see screenshots) 
- Randomly error or build success on my windows 11 work station
- Not yet on my mac laptop (m1)

The randomness on my windows machine sort of feels like there is some kind race condition going on. I have spent some hours yesterday and most of today trying to detect a pattern. Trying to build many different commits in our repo, and three different Astro versions,  but I am havent found anything predictable to trigger/not trigger the error on my work station. I have seen it triggered with Astro versions `2.3.0`, `2.3.3` and `2.3.4`. 

node `16.17.0` for all environments
npm workspace/monorepo structure if that matters

![image](https://user-images.githubusercontent.com/1263775/235952077-e3976c5a-2b59-4c92-9814-ca8737a4dac0.png)

**Comment by petterhoel** [comment]
Another update: This seems to be a windows only issue. I have tested on macs and linux (running the build on netlify) with no issues.

**Comment by maddsua** [comment]
In my case a pattern like this causes the issue
![изображение](https://user-images.githubusercontent.com/102395937/236698494-faffd600-ae9b-4f9e-b4c3-98ade4621af5.png)

Worked OK on v2.3.1, crashes on 2.4.2

**Comment by maddsua** [comment]
> In my case a pattern like this causes the issue ![изображение](https://user-images.githubusercontent.com/102395937/236698494-faffd600-ae9b-4f9e-b4c3-98ade4621af5.png)
> 
> Worked OK on v2.3.1, crashes on 2.4.2

<details>

<summary>Stacktrace</summary>

````
goroutine 64 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x47a240, {0x1918040, 0x4864c8})
	github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
	./astro-wasm.go:284 +0x5
panic({0x2dae0, 0x4864c8})
	runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal/printer.(*printer).printTextWithSourcemap(0x6a1758, {0x620b00, 0x3a}, {0x21a})
	github.com/withastro/compiler/internal/printer/printer.go:72 +0x25
github.com/withastro/compiler/internal/printer.render1(0x6a1758, 0x6df540, {0x0, 0x0, 0x5, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:320 +0x18f
github.com/withastro/compiler/internal/printer.render1(0x6a1758, 0x6dec80, {0x0, 0x0, 0x4, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x6a1758, 0x6dea00, {0x0, 0x0, 0x3, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x6a1758, 0x6de8c0, {0x0, 0x0, 0x2, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x6a1758, 0x6de640, {0x0, 0x0, 0x1, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:696 +0x53d
github.com/withastro/compiler/internal/printer.render1(0x6a1758, 0x6de140, {0x1, 0x0, 0x0, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:121 +0xc1
github.com/withastro/compiler/internal/printer.printToJs(0x6a1758, 0x6de140, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, {0x6208c0, 0x33}, {0x486240, ...}, ...})
	github.com/withastro/compiler/internal/printer/print-to-js.go:72 +0x3
github.com/withastro/compiler/internal/printer.PrintToJS({0x5d7500, 0x1429}, 0x6de140, 0x1, {{0x5c0350, 0x8}, {0x4ae4b0, 0x45}, {0x6208c0, 0x33}, ...}, ...)
	github.com/withastro/compiler/internal/printer/print-to-js.go:53 +0xc
main.Transform.func1.1.1()
	./astro-wasm.go:401 +0x38
created by main.Transform.func1.1
	./astro-wasm.go:280 +0x14
```

</details>

**Comment by maddsua** [comment]
> In my case a pattern like this causes the issue ![изображение](https://user-images.githubusercontent.com/102395937/236698494-faffd600-ae9b-4f9e-b4c3-98ade4621af5.png)
> 
> Worked OK on v2.3.1, crashes on 2.4.2

Very interesting... In my case, changing `....getTime() / 1000` to `....getTime() * 0.001` seems to solve the issue

**Comment by SubratKumarGupta** [comment]
I am getting the same issue on wsl2 with Ubuntu and node v20.1.0, Astro 2.4.2,

```   Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.
  File:
    /mnt/c/Users/SUBRAT/Desktop/projects/subratgupta-portfolio/src/components/Sidebar/nav.astro 
```
this is the project https://github.com/SubratKumarGupta/subratgupta-portfolio
