### ISSUE TITLE
🐛 BUG:  runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by brian727** [withastro/compiler#883]
### What version of `@astrojs/compiler` are you using?

2.2.2

### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Trying to build out blog in the Documentation tutorial with npm run build but getting the error. 

![Uploading image.png…]()

 astro-blog@0.0.1 dev
> astro dev

   astro  v3.4.3 started in 242ms

  ┃ Local    http://localhost:4321/
  ┃ Network  use --host to expose

 error   runtime error: index out of range [0] with length 0
  Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.   
  Error reference:
    https://docs.astro.build/en/reference/errors/unknown-compiler-error/
  File:
    C:/Users/brian/OneDrive/Desktop/astro-blog/src/pages/about.astro
  Stacktrace:
goroutine 8 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x47a900, {0xb110d8, 0x4862e8})
        github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
        ./astro-wasm.go:290 +0x5
panic({0x2db80, 0x4862e8})
        runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal.inBodyIM(0x47aa20)
        github.com/withastro/compiler/internal/parser.go:1157 +0x658
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x47aa20)
        github.com/withastro/compiler/internal/parser.go:2968 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x47aa20)
        github.com/withastro/compiler/internal/parser.go:2995 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x7b858, 0x42c1e0}, {0x439b80, 0x1, 0x1})
        github.com/withastro/compiler/internal/parser.go:3059 +0x1c
main.Transform.func1.1.1()
        ./astro-wasm.go:295 +0xc
created by main.Transform.func1.1
        ./astro-wasm.go:286 +0x14

 error   runtime error: index out of range [0] with length 0
  Hint:
    This is almost always a problem with the Astro compiler, not your code. Please open an issue at https://astro.build/issues/compiler.   
  Error reference:
    https://docs.astro.build/en/reference/errors/unknown-compiler-error/
  File:
    C:/Users/brian/OneDrive/Desktop/astro-blog/src/pages/about.astro
  Stacktrace:
goroutine 9 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x47ab40, {0xb110d8, 0x4864b0})
        github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
        ./astro-wasm.go:290 +0x5
panic({0x2db80, 0x4864b0})
        runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal.inBodyIM(0x47ac60)
        github.com/withastro/compiler/internal/parser.go:1157 +0x658
github.com/withastro/compiler/internal.(*parser).parseCurrentToken(0x47ac60)
        github.com/withastro/compiler/internal/parser.go:2968 +0x13
github.com/withastro/compiler/internal.(*parser).parse(0x47ac60)
        github.com/withastro/compiler/internal/parser.go:2995 +0x3
github.com/withastro/compiler/internal.ParseWithOptions({0x7b858, 0x42c2a0}, {0x439b80, 0x1, 0x1})
        github.com/withastro/compiler/internal/parser.go:3059 +0x1c
main.Transform.func1.1.1()
        ./astro-wasm.go:295 +0xc
created by main.Transform.func1.1
        ./astro-wasm.go:286 +0x14

### Link to Minimal Reproducible Example

https://github.com/brian727/astro-blog

**Comment by brian727** [comment]
Closing this. Operator error.
