### ISSUE TITLE
🐛 BUG: Quoted markup in frontmatter causes a panic

### ISSUE THREAD

**Issue by natemoo-re** [withastro/compiler#920]
### What version of `@astrojs/compiler` are you using?

2.0.0

### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

User reported error on Discord that causes a very weird `panic`. I opened https://github.com/withastro/compiler/pull/919 to try to debug this, but wasn't able to reproduce it for myself. Seems to have something to do with HTML embedded in an object inside of the frontmatter.

```
Stacktrace:
goroutine 106 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x6
github.com/withastro/compiler/internal_wasm/utils.ErrorToJSError(0x1026900, {0xaec3a5d8, 0x90ffe7b0})
        github.com/withastro/compiler/internal_wasm/utils/utils.go:68 +0x2
main.Transform.func1.1.1.1()
        ./astro-wasm.go:290 +0x5
panic({0x2db80, 0x90ffe7b0})
        runtime/panic.go:884 +0x29
github.com/withastro/compiler/internal.(*Tokenizer).readUnclosedTag(0x11dda00)
        github.com/withastro/compiler/internal/token.go:1257 +0x30
github.com/withastro/compiler/internal.(*Tokenizer).Next(0x11dda00)
        github.com/withastro/compiler/internal/token.go:1764 +0x94
github.com/withastro/compiler/internal.(*parser).parse(0x1026a20)
        github.com/withastro/compiler/internal/parser.go:2987 +0x1e
github.com/withastro/compiler/internal.ParseWithOptions({0x7b7c8, 0x42c9a0}, {0x436b80, 0x1, 0x1})
        github.com/withastro/compiler/internal/parser.go:3059 +0x1c
main.Transform.func1.1.1()
        ./astro-wasm.go:295 +0xc
created by main.Transform.func1.1
        ./astro-wasm.go:286 +0x14
```

### Link to Minimal Reproducible Example

please forgive me

**Comment by MoustaphaDev** [comment]
No reproduction 😠, closing now!!

**Comment by Princesseuh** [comment]
Hello, the Go compiler for Astro is no longer maintained. All future development will be focused on [our new Rust compiler](https://github.com/withastro/compiler-rs). If this issue is still relevant and you can reproduce it on the Rust compiler, please open a new issue there. Thank you!
